Applications of Majorization Theory
> CDMA Sequence Design illustration


---



Done by Haritha.R ( AI20BTECH11010 ) 

In [283]:
import numpy as np
import math 


In [284]:

# Problem data.
K = 3
N = 4    # N >=K
p = np.random.randint(10,size=K)
sigma= np.random.random(1)[0]  


print("K = ",K,",N = ",N,"sigma=",sigma,"\n")
P= np.zeros((K,K))
for i in range(K):
      P[i,i]=p[i]
      print("p",i+1," = ",round(p[i],4))


S=np.array([[1, (1/math.sqrt(2)) , 1/2],
   [0, (1/math.sqrt(2)) , 1/2],
   [0, 0 , 1/2],
   [0, 0 , 1/2]])

print("\nColumn wise norms of S:")
norm_S= np.linalg.norm(S, axis = 0)
for i in range(K):
    print(" ||s",i+1,"|| =",round(norm_S[i] ))

A=np.dot(np.dot(S,P) ,S.T)
print("\n SP(S^T) =\n ",A)

Eigen_values_lambdas,Eigen_vectors=np.linalg.eig(A)

print("\nEigen Values of SP(S^T) =")
for i in range(N):
     print("lamda",i+1,"=",round(Eigen_values_lambdas[i],4))


lamda=Eigen_values_lambdas[:K]

p.sort()
p_cum_sum =np.cumsum(p)

lamda.sort()
lambda_cum_sum=np.cumsum(lamda)
 
print("\n cumulative sum of p in ascending order=",p_cum_sum,"\ncumulative sum of lambda in ascending order=",lambda_cum_sum)
if((lambda_cum_sum <= p_cum_sum).all):
  print("clearly lambda majorises p ")

twsc = sum(np.square(Eigen_values_lambdas))

mse=K
c_sum=0
for i in range(N):
  l=Eigen_values_lambdas[i]
  c_sum = c_sum + (( math.log(1+ l/(sigma*sigma)) )/2)
  mse= mse - (l /(l + (sigma*sigma)) )

print("mimimum TWSC=",twsc,"\n minimum MMSE=",mse,"\n maximum sum capacity=",c_sum)  

K =  3 ,N =  4 sigma= 0.35768229296515897 

p 1  =  6
p 2  =  7
p 3  =  9

Column wise norms of S:
 ||s 1 || = 1
 ||s 2 || = 1
 ||s 3 || = 1

 SP(S^T) =
  [[11.75  5.75  2.25  2.25]
 [ 5.75  5.75  2.25  2.25]
 [ 2.25  2.25  2.25  2.25]
 [ 2.25  2.25  2.25  2.25]]

Eigen Values of SP(S^T) =
lamda 1 = 16.7987
lamda 2 = 3.6673
lamda 3 = 1.5339
lamda 4 = 0.0

 cumulative sum of p in ascending order= [ 6 13 22] 
cumulative sum of lambda in ascending order= [ 1.53392909  5.20125696 22.        ]
clearly lambda majorises p 
mimimum TWSC= 297.99999999999994 
 minimum MMSE= 0.11825155393968478 
 maximum sum capacity= 5.419623434839098
